// Human wording for engine flags. Tone drives chip colour.
type Tone = 'danger' | 'caution' | 'info' | undefined;

export const LINK_FLAGS: Record<string, [string, Tone]> = {
  'threat-intel': ['Threat feed', 'danger'],
  'text-href-mismatch': ['Text ≠ destination', 'danger'],
  'text-href-mismatch-tracking': ['Via click tracker', undefined],
  'lookalike-homoglyph': ['Homoglyph domain', 'danger'],
  'lookalike-typosquat': ['Typosquat domain', 'danger'],
  'lookalike-embedded': ['Brand decoy', 'caution'],
  'lookalike-subdomain': ['Brand in subdomain', 'caution'],
  'ip-host': ['Raw IP address', 'danger'],
  'private-ip-host': ['Private IP', 'danger'],
  punycode: ['Punycode', 'caution'],
  'mixed-script': ['Mixed alphabets', 'danger'],
  'credentials-in-url': ['@ disguise', 'danger'],
  'javascript-uri': ['Runs JavaScript', 'danger'],
  'data-uri': ['Inline data', 'danger'],
  'vbscript-uri': ['Runs VBScript', 'danger'],
  'file-uri': ['Local file', 'danger'],
  'nonstandard-port': ['Unusual port', 'caution'],
  'file-download': ['Risky download', 'caution'],
  ipfs: ['IPFS hosting', 'caution'],
  'free-hosting': ['Free web host', 'caution'],
  'form-service': ['Form builder', 'caution'],
  shortener: ['Shortened', 'info'],
  'suspicious-tld': ['High-abuse TLD', 'info'],
  'deep-subdomain': ['Deep subdomain', 'info'],
  'redirect-param': ['Redirects onward', 'info'],
  'no-tls': ['No HTTPS', undefined],
  'long-url': ['Very long', undefined],
  'login-keywords': ['Login wording', undefined],
  tracking: ['Tracking', undefined],
  unsubscribe: ['Unsubscribe', undefined],
  'esp-tracking': ['Mail tracker', undefined],
};

export const FILE_FLAGS: Record<string, [string, Tone]> = {
  executable: ['Executable', 'danger'],
  'double-extension': ['Double extension', 'danger'],
  'rtlo-filename': ['Reversed filename', 'danger'],
  'padded-filename': ['Padded filename', 'danger'],
  'disk-image': ['Disk image', 'danger'],
  'archive-executable': ['Executable inside', 'danger'],
  'archive-disk-image': ['Disk image inside', 'danger'],
  'html-credential-form': ['Login form', 'danger'],
  'html-smuggling-script': ['Smuggling script', 'danger'],
  'office-macros': ['Macros', 'danger'],
  'office-remote-template': ['Remote template', 'danger'],
  'office-dde': ['DDE field', 'danger'],
  'rtf-embedded-object': ['Embedded object', 'danger'],
  'pdf-autorun-script': ['Auto-run script', 'danger'],
  'type-mismatch': ['Type mismatch', 'caution'],
  'macro-enabled-office': ['Macro-enabled', 'caution'],
  onenote: ['OneNote file', 'caution'],
  'encrypted-archive': ['Password-protected', 'caution'],
  'encrypted-office': ['Encrypted document', 'caution'],
  'office-ole-object': ['OLE object', 'caution'],
  'office-activex': ['ActiveX', 'caution'],
  'archive-html': ['HTML inside', 'caution'],
  'archive-macro-office': ['Macro doc inside', 'caution'],
  'html-attachment': ['Web page file', 'caution'],
  'svg-attachment': ['SVG file', 'caution'],
  'html-form': ['Form', 'caution'],
  'html-redirect': ['Redirect', 'caution'],
  'pdf-javascript': ['PDF JavaScript', 'caution'],
  'pdf-openaction': ['Auto-action', 'caution'],
  'pdf-auto-action': ['Auto-action', 'caution'],
  'pdf-launch': ['Launch action', 'caution'],
  'qr-code': ['QR code', 'caution'],
  'pdf-embedded-file': ['Embedded file', 'info'],
  'pdf-form': ['PDF form', 'info'],
  'pdf-xfa': ['XFA form', 'info'],
  'pdf-submitform': ['Submits data', 'caution'],
  'pdf-link-lure': ['Link lure', 'info'],
  'pdf-object-streams': ['Object streams', undefined],
  'nested-archive': ['Nested archive', 'info'],
  'uninspectable-archive': ['Can’t inspect', 'info'],
  'calendar-links': ['Calendar links', 'info'],
  'attached-email': ['Attached email', 'info'],
  'not-inspected-size': ['Too large to inspect', undefined],
};

export const INTENT_LABELS: Record<string, string> = {
  credential: 'Credential harvesting',
  payment: 'Payment / invoice fraud',
  giftcard: 'Gift-card scam',
  crypto: 'Crypto theft',
  mfa: 'MFA / device-code theft',
  delivery: 'Delivery scam',
  document: 'Fake shared document',
  tax: 'Tax / government lure',
  job: 'Job / task scam',
  reward: 'Prize / reward lure',
  extortion: 'Extortion',
  callback: 'Call-back scam',
  bec: 'CEO / business email compromise',
};

export function flagLabel(map: Record<string, [string, Tone]>, flag: string): [string, Tone] {
  return map[flag] ?? [flag.replace(/-/g, ' '), undefined];
}
